{% set name = "pykwalify" %}
{% set version = "1.8.0" %}
{% set checksum = "796b2ad3ed4cb99b88308b533fb2f559c30fa6efb4fa9fda11347f483d245884" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pykwalify = pykwalify.cli:cli_entrypoint

requirements:
  host:
    - python
    - pip

  run:
    - python
    - docopt >=0.6.2
    - pyyaml >=3.11
    - python-dateutil >=2.4.2

test:
  imports:
    - pykwalify

  commands:
    - pykwalify --help

about:
  home: http://github.com/grokzen/pykwalify
  license: MIT
  license_file: LICENSE
  summary: Python lib/cli for JSON/YAML schema validation

extra:
  recipe-maintainers:
    - jakirkham
